### ISSUE TITLE
MelonDS does not compile on Ubuntu 18.04 (and QT before 5.10) due to missing QThread::Create function

### ISSUE THREAD

**Issue by man-of-eel** [StapleButter/melonDS#1192]
https://github.com/Arisotura/melonDS/blob/b40ff12a608eceb21421599bc1f82734ee3b25b2/src/frontend/qt_sdl/Platform.cpp#L192

The line above causes compilation to fail with
error: ‘create’ is not a member of ‘QThread’
since QThread::Create was not added until QT 5.10 which isn't available on 18.04 (I've tried).

This is the only instance of it so it can probably be replaced but I'm not familiar enough with QT

**Comment by nadiaholmquist** [comment]
We're not really interested in workarounds to support such old versions of libraries. I'd suggest using the flatpak version or a newer version of your distro that ships a newer version of Qt.
